// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/generate-bindings.py from docs/derived-core-schema.json -- DO NOT EDIT.
#include "generated.h"

using namespace odb;

namespace {
static std::string gs(rust::Str v) { return std::string(v.data(), v.size()); }
static odb::dbBlock* gen_block(const OdbDb& h) {
  odb::dbChip* c = h.db->getChip(); return c ? c->getBlock() : nullptr; }
static odb::dbInst* gen_inst(const OdbDb& h, rust::Str n) {
  odb::dbBlock* b = gen_block(h); return b ? b->findInst(gs(n).c_str()) : nullptr; }
static odb::dbNet* gen_net(const OdbDb& h, rust::Str n) {
  odb::dbBlock* b = gen_block(h); return b ? b->findNet(gs(n).c_str()) : nullptr; }
static odb::dbBTerm* gen_bterm(const OdbDb& h, rust::Str n) {
  odb::dbBlock* b = gen_block(h); return b ? b->findBTerm(gs(n).c_str()) : nullptr; }
}  // namespace

rust::String block_get_name(const OdbDb& h) { auto* p = gen_block(h); return p ? rust::String(p->getName()) : rust::String(); }
rust::String block_get_const_name(const OdbDb& h) { auto* p = gen_block(h); if (!p) return rust::String(); const char* v = p->getConstName(); return rust::String(v ? v : ""); }
rust::String block_get_tech(const OdbDb& h) { auto* p = gen_block(h); if (!p) return rust::String(); auto* t = p->getTech(); return t ? rust::String(t->getName()) : rust::String(); }
rust::String block_get_parent(const OdbDb& h) { auto* p = gen_block(h); if (!p) return rust::String(); auto* t = p->getParent(); return t ? rust::String(t->getConstName()) : rust::String(); }
rust::String block_get_parent_inst(const OdbDb& h) { auto* p = gen_block(h); if (!p) return rust::String(); auto* t = p->getParentInst(); return t ? rust::String(t->getConstName()) : rust::String(); }
std::size_t num_block_get_children(const OdbDb& h) { auto* p = gen_block(h); return p ? p->getChildren().size() : 0; }
rust::String nth_block_get_children(const OdbDb& h, std::size_t i) { auto* p = gen_block(h); if (!p) return rust::String(); std::size_t k = 0; for (auto* e : p->getChildren()) { if (k++ == i) return rust::String(e->getConstName()); } return rust::String(); }
std::size_t num_block_get_b_terms(const OdbDb& h) { auto* p = gen_block(h); return p ? p->getBTerms().size() : 0; }
rust::String nth_block_get_b_terms(const OdbDb& h, std::size_t i) { auto* p = gen_block(h); if (!p) return rust::String(); std::size_t k = 0; for (auto* e : p->getBTerms()) { if (k++ == i) return rust::String(e->getConstName()); } return rust::String(); }
std::size_t num_block_get_i_terms(const OdbDb& h) { auto* p = gen_block(h); return p ? p->getITerms().size() : 0; }
rust::String nth_block_get_i_terms(const OdbDb& h, std::size_t i) { auto* p = gen_block(h); if (!p) return rust::String(); std::size_t k = 0; for (auto* e : p->getITerms()) { if (k++ == i) return rust::String((e->getInst()->getName() + "/" + e->getMTerm()->getName())); } return rust::String(); }
std::size_t num_block_get_insts(const OdbDb& h) { auto* p = gen_block(h); return p ? p->getInsts().size() : 0; }
rust::String nth_block_get_insts(const OdbDb& h, std::size_t i) { auto* p = gen_block(h); if (!p) return rust::String(); std::size_t k = 0; for (auto* e : p->getInsts()) { if (k++ == i) return rust::String(e->getConstName()); } return rust::String(); }
std::size_t num_block_get_mod_nets(const OdbDb& h) { auto* p = gen_block(h); return p ? p->getModNets().size() : 0; }
rust::String nth_block_get_mod_nets(const OdbDb& h, std::size_t i) { auto* p = gen_block(h); if (!p) return rust::String(); std::size_t k = 0; for (auto* e : p->getModNets()) { if (k++ == i) return rust::String(e->getConstName()); } return rust::String(); }
std::size_t num_block_get_nets(const OdbDb& h) { auto* p = gen_block(h); return p ? p->getNets().size() : 0; }
rust::String nth_block_get_nets(const OdbDb& h, std::size_t i) { auto* p = gen_block(h); if (!p) return rust::String(); std::size_t k = 0; for (auto* e : p->getNets()) { if (k++ == i) return rust::String(e->getConstName()); } return rust::String(); }
std::size_t num_block_get_vias(const OdbDb& h) { auto* p = gen_block(h); return p ? p->getVias().size() : 0; }
rust::String nth_block_get_vias(const OdbDb& h, std::size_t i) { auto* p = gen_block(h); if (!p) return rust::String(); std::size_t k = 0; for (auto* e : p->getVias()) { if (k++ == i) return rust::String(e->getConstName()); } return rust::String(); }
int32_t block_get_def_units(const OdbDb& h) { auto* p = gen_block(h); return p ? p->getDefUnits() : 0; }
int32_t block_get_db_units_per_micron(const OdbDb& h) { auto* p = gen_block(h); return p ? p->getDbUnitsPerMicron() : 0; }
int32_t block_get_corner_count(const OdbDb& h) { auto* p = gen_block(h); return p ? p->getCornerCount() : 0; }
int32_t block_get_corners_per_block(const OdbDb& h) { auto* p = gen_block(h); return p ? p->getCornersPerBlock() : 0; }
int32_t block_get_ext_db_count(const OdbDb& h) { auto* p = gen_block(h); return p ? p->getExtDbCount() : 0; }
rust::String block_get_corner_name_list(const OdbDb& h) { auto* p = gen_block(h); if (!p) return rust::String(); const char* v = p->getCornerNameList(); return rust::String(v ? v : ""); }
std::size_t num_block_get_rows(const OdbDb& h) { auto* p = gen_block(h); return p ? p->getRows().size() : 0; }
rust::String nth_block_get_rows(const OdbDb& h, std::size_t i) { auto* p = gen_block(h); if (!p) return rust::String(); std::size_t k = 0; for (auto* e : p->getRows()) { if (k++ == i) return rust::String(e->getConstName()); } return rust::String(); }
int32_t block_get_min_routing_layer(const OdbDb& h) { auto* p = gen_block(h); return p ? p->getMinRoutingLayer() : 0; }
int32_t block_get_max_routing_layer(const OdbDb& h) { auto* p = gen_block(h); return p ? p->getMaxRoutingLayer() : 0; }
int32_t block_get_min_layer_for_clock(const OdbDb& h) { auto* p = gen_block(h); return p ? p->getMinLayerForClock() : 0; }
int32_t block_get_max_layer_for_clock(const OdbDb& h) { auto* p = gen_block(h); return p ? p->getMaxLayerForClock() : 0; }
int32_t block_get_g_cell_tile_size(const OdbDb& h) { auto* p = gen_block(h); return p ? p->getGCellTileSize() : 0; }
std::size_t num_block_get_regions(const OdbDb& h) { auto* p = gen_block(h); return p ? p->getRegions().size() : 0; }
rust::String nth_block_get_regions(const OdbDb& h, std::size_t i) { auto* p = gen_block(h); if (!p) return rust::String(); std::size_t k = 0; for (auto* e : p->getRegions()) { if (k++ == i) return rust::String(e->getName()); } return rust::String(); }
std::size_t num_block_get_non_default_rules(const OdbDb& h) { auto* p = gen_block(h); return p ? p->getNonDefaultRules().size() : 0; }
rust::String nth_block_get_non_default_rules(const OdbDb& h, std::size_t i) { auto* p = gen_block(h); if (!p) return rust::String(); std::size_t k = 0; for (auto* e : p->getNonDefaultRules()) { if (k++ == i) return rust::String(e->getConstName()); } return rust::String(); }
rust::String inst_get_name(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); return p ? rust::String(p->getName()) : rust::String(); }
rust::String inst_get_const_name(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); if (!p) return rust::String(); const char* v = p->getConstName(); return rust::String(v ? v : ""); }
rust::String inst_get_orient(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); return p ? rust::String(p->getOrient().getString()) : rust::String(); }
rust::String inst_get_placement_status(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); return p ? rust::String(p->getPlacementStatus().getString()) : rust::String(); }
bool inst_is_fixed(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); return p ? p->isFixed() : false; }
bool inst_is_placed(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); return p ? p->isPlaced() : false; }
bool inst_get_eco_create(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); return p ? p->getEcoCreate() : false; }
bool inst_get_eco_destroy(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); return p ? p->getEcoDestroy() : false; }
bool inst_get_eco_modify(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); return p ? p->getEcoModify() : false; }
bool inst_get_user_flag1(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); return p ? p->getUserFlag1() : false; }
bool inst_get_user_flag2(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); return p ? p->getUserFlag2() : false; }
bool inst_get_user_flag3(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); return p ? p->getUserFlag3() : false; }
bool inst_is_do_not_touch(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); return p ? p->isDoNotTouch() : false; }
rust::String inst_get_block(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); if (!p) return rust::String(); auto* t = p->getBlock(); return t ? rust::String(t->getConstName()) : rust::String(); }
rust::String inst_get_master(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); if (!p) return rust::String(); auto* t = p->getMaster(); return t ? rust::String(t->getConstName()) : rust::String(); }
std::size_t num_inst_get_i_terms(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); return p ? p->getITerms().size() : 0; }
rust::String nth_inst_get_i_terms(const OdbDb& h, rust::Str inst, std::size_t i) { auto* p = gen_inst(h, inst); if (!p) return rust::String(); std::size_t k = 0; for (auto* e : p->getITerms()) { if (k++ == i) return rust::String((e->getInst()->getName() + "/" + e->getMTerm()->getName())); } return rust::String(); }
rust::String inst_get_first_input(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); if (!p) return rust::String(); auto* t = p->getFirstInput(); return t ? rust::String((t->getInst()->getName() + "/" + t->getMTerm()->getName())) : rust::String(); }
rust::String inst_get_first_output(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); if (!p) return rust::String(); auto* t = p->getFirstOutput(); return t ? rust::String((t->getInst()->getName() + "/" + t->getMTerm()->getName())) : rust::String(); }
rust::String inst_get_region(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); if (!p) return rust::String(); auto* t = p->getRegion(); return t ? rust::String(t->getName()) : rust::String(); }
rust::String inst_get_child(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); if (!p) return rust::String(); auto* t = p->getChild(); return t ? rust::String(t->getConstName()) : rust::String(); }
rust::String inst_get_parent(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); if (!p) return rust::String(); auto* t = p->getParent(); return t ? rust::String(t->getConstName()) : rust::String(); }
std::size_t num_inst_get_children(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); return p ? p->getChildren().size() : 0; }
rust::String nth_inst_get_children(const OdbDb& h, rust::Str inst, std::size_t i) { auto* p = gen_inst(h, inst); if (!p) return rust::String(); std::size_t k = 0; for (auto* e : p->getChildren()) { if (k++ == i) return rust::String(e->getConstName()); } return rust::String(); }
bool inst_is_hierarchical(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); return p ? p->isHierarchical() : false; }
bool inst_is_physical_only(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); return p ? p->isPhysicalOnly() : false; }
int32_t inst_get_weight(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); return p ? p->getWeight() : 0; }
rust::String inst_get_source_type(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); return p ? rust::String(p->getSourceType().getString()) : rust::String(); }
bool inst_is_block(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); return p ? p->isBlock() : false; }
bool inst_is_core(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); return p ? p->isCore() : false; }
bool inst_is_pad(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); return p ? p->isPad() : false; }
bool inst_is_end_cap(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); return p ? p->isEndCap() : false; }
uint32_t inst_get_pin_access_idx(const OdbDb& h, rust::Str inst) { auto* p = gen_inst(h, inst); return p ? p->getPinAccessIdx() : 0; }
rust::String net_get_name(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? rust::String(p->getName()) : rust::String(); }
rust::String net_get_const_name(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); if (!p) return rust::String(); const char* v = p->getConstName(); return rust::String(v ? v : ""); }
bool net_is_r_c_disconnected(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->isRCDisconnected() : false; }
int32_t net_get_weight(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->getWeight() : 0; }
rust::String net_get_source_type(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? rust::String(p->getSourceType().getString()) : rust::String(); }
int32_t net_get_x_talk_class(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->getXTalkClass() : 0; }
rust::String net_get_driving_i_term(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); if (!p) return rust::String(); auto* t = p->getDrivingITerm(); return t ? rust::String((t->getInst()->getName() + "/" + t->getMTerm()->getName())) : rust::String(); }
bool net_has_fixed_bump(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->hasFixedBump() : false; }
rust::String net_get_wire_type(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? rust::String(p->getWireType().getString()) : rust::String(); }
rust::String net_get_sig_type(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? rust::String(p->getSigType().getString()) : rust::String(); }
bool net_is_marked(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->isMarked() : false; }
bool net_is_mark_1ed(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->isMark_1ed() : false; }
bool net_is_select(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->isSelect() : false; }
bool net_is_wire_ordered(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->isWireOrdered() : false; }
bool net_is_disconnected(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->isDisconnected() : false; }
bool net_is_wire_altered(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->isWireAltered() : false; }
bool net_is_r_cgraph(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->isRCgraph() : false; }
bool net_is_extracted(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->isExtracted() : false; }
bool net_is_spef(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->isSpef() : false; }
bool net_is_do_not_touch(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->isDoNotTouch() : false; }
rust::String net_get_block(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); if (!p) return rust::String(); auto* t = p->getBlock(); return t ? rust::String(t->getConstName()) : rust::String(); }
std::size_t num_net_get_i_terms(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->getITerms().size() : 0; }
rust::String nth_net_get_i_terms(const OdbDb& h, rust::Str net, std::size_t i) { auto* p = gen_net(h, net); if (!p) return rust::String(); std::size_t k = 0; for (auto* e : p->getITerms()) { if (k++ == i) return rust::String((e->getInst()->getName() + "/" + e->getMTerm()->getName())); } return rust::String(); }
rust::String net_get1st_i_term(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); if (!p) return rust::String(); auto* t = p->get1stITerm(); return t ? rust::String((t->getInst()->getName() + "/" + t->getMTerm()->getName())) : rust::String(); }
rust::String net_get_first_driver_inst(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); if (!p) return rust::String(); auto* t = p->getFirstDriverInst(); return t ? rust::String(t->getConstName()) : rust::String(); }
rust::String net_get_first_output(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); if (!p) return rust::String(); auto* t = p->getFirstOutput(); return t ? rust::String((t->getInst()->getName() + "/" + t->getMTerm()->getName())) : rust::String(); }
std::size_t num_net_get_b_terms(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->getBTerms().size() : 0; }
rust::String nth_net_get_b_terms(const OdbDb& h, rust::Str net, std::size_t i) { auto* p = gen_net(h, net); if (!p) return rust::String(); std::size_t k = 0; for (auto* e : p->getBTerms()) { if (k++ == i) return rust::String(e->getConstName()); } return rust::String(); }
rust::String net_get1st_b_term(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); if (!p) return rust::String(); auto* t = p->get1stBTerm(); return t ? rust::String(t->getConstName()) : rust::String(); }
bool net_is_connected_by_abutment(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->isConnectedByAbutment() : false; }
bool net_is_i_o(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->isIO() : false; }
bool net_is_wild_connected(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->isWildConnected() : false; }
float net_get_gndc_calib_factor(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->getGndcCalibFactor() : 0.0f; }
float net_get_cc_calib_factor(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->getCcCalibFactor() : 0.0f; }
float net_get_cc_adjust_factor(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->getCcAdjustFactor() : 0.0f; }
uint32_t net_get_cc_adjust_order(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->getCcAdjustOrder() : 0; }
float net_get_db_cc(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->getDbCc() : 0.0f; }
float net_get_ref_cc(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->getRefCc() : 0.0f; }
float net_get_cc_match_ratio(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->getCcMatchRatio() : 0.0f; }
uint32_t net_get1st_r_seg_id(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->get1stRSegId() : 0; }
uint32_t net_get1st_cap_node_id(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->get1stCapNodeId() : 0; }
uint32_t net_get_r_seg_count(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->getRSegCount() : 0; }
uint32_t net_max_internal_cap_num(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->maxInternalCapNum() : 0; }
uint32_t net_get_cap_node_count(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->getCapNodeCount() : 0; }
uint32_t net_get_cc_count(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->getCcCount() : 0; }
rust::String net_get_non_default_rule(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); if (!p) return rust::String(); auto* t = p->getNonDefaultRule(); return t ? rust::String(t->getConstName()) : rust::String(); }
uint32_t net_get_term_count(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->getTermCount() : 0; }
uint32_t net_get_i_term_count(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->getITermCount() : 0; }
uint32_t net_get_b_term_count(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->getBTermCount() : 0; }
bool net_has_jumpers(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); return p ? p->hasJumpers() : false; }
rust::String net_find_mod_net_in_highest_hier(const OdbDb& h, rust::Str net) { auto* p = gen_net(h, net); if (!p) return rust::String(); auto* t = p->findModNetInHighestHier(); return t ? rust::String(t->getConstName()) : rust::String(); }
rust::String bterm_get_name(const OdbDb& h, rust::Str bterm) { auto* p = gen_bterm(h, bterm); return p ? rust::String(p->getName()) : rust::String(); }
rust::String bterm_get_const_name(const OdbDb& h, rust::Str bterm) { auto* p = gen_bterm(h, bterm); if (!p) return rust::String(); const char* v = p->getConstName(); return rust::String(v ? v : ""); }
rust::String bterm_get_sig_type(const OdbDb& h, rust::Str bterm) { auto* p = gen_bterm(h, bterm); return p ? rust::String(p->getSigType().getString()) : rust::String(); }
rust::String bterm_get_io_type(const OdbDb& h, rust::Str bterm) { auto* p = gen_bterm(h, bterm); return p ? rust::String(p->getIoType().getString()) : rust::String(); }
bool bterm_is_set_spef_mark(const OdbDb& h, rust::Str bterm) { auto* p = gen_bterm(h, bterm); return p ? p->isSetSpefMark() : false; }
bool bterm_is_set_mark(const OdbDb& h, rust::Str bterm) { auto* p = gen_bterm(h, bterm); return p ? p->isSetMark() : false; }
uint32_t bterm_get_ext_id(const OdbDb& h, rust::Str bterm) { auto* p = gen_bterm(h, bterm); return p ? p->getExtId() : 0; }
bool bterm_is_special(const OdbDb& h, rust::Str bterm) { auto* p = gen_bterm(h, bterm); return p ? p->isSpecial() : false; }
rust::String bterm_get_net(const OdbDb& h, rust::Str bterm) { auto* p = gen_bterm(h, bterm); if (!p) return rust::String(); auto* t = p->getNet(); return t ? rust::String(t->getConstName()) : rust::String(); }
rust::String bterm_get_mod_net(const OdbDb& h, rust::Str bterm) { auto* p = gen_bterm(h, bterm); if (!p) return rust::String(); auto* t = p->getModNet(); return t ? rust::String(t->getConstName()) : rust::String(); }
rust::String bterm_get_block(const OdbDb& h, rust::Str bterm) { auto* p = gen_bterm(h, bterm); if (!p) return rust::String(); auto* t = p->getBlock(); return t ? rust::String(t->getConstName()) : rust::String(); }
rust::String bterm_get_i_term(const OdbDb& h, rust::Str bterm) { auto* p = gen_bterm(h, bterm); if (!p) return rust::String(); auto* t = p->getITerm(); return t ? rust::String((t->getInst()->getName() + "/" + t->getMTerm()->getName())) : rust::String(); }
rust::String bterm_get_first_pin_placement_status(const OdbDb& h, rust::Str bterm) { auto* p = gen_bterm(h, bterm); return p ? rust::String(p->getFirstPinPlacementStatus().getString()) : rust::String(); }
rust::String bterm_get_ground_pin(const OdbDb& h, rust::Str bterm) { auto* p = gen_bterm(h, bterm); if (!p) return rust::String(); auto* t = p->getGroundPin(); return t ? rust::String(t->getConstName()) : rust::String(); }
rust::String bterm_get_supply_pin(const OdbDb& h, rust::Str bterm) { auto* p = gen_bterm(h, bterm); if (!p) return rust::String(); auto* t = p->getSupplyPin(); return t ? rust::String(t->getConstName()) : rust::String(); }
uint32_t bterm_sta_vertex_id(const OdbDb& h, rust::Str bterm) { auto* p = gen_bterm(h, bterm); return p ? p->staVertexId() : 0; }
rust::String bterm_get_mirrored_b_term(const OdbDb& h, rust::Str bterm) { auto* p = gen_bterm(h, bterm); if (!p) return rust::String(); auto* t = p->getMirroredBTerm(); return t ? rust::String(t->getConstName()) : rust::String(); }
bool bterm_has_mirrored_b_term(const OdbDb& h, rust::Str bterm) { auto* p = gen_bterm(h, bterm); return p ? p->hasMirroredBTerm() : false; }
bool bterm_is_mirrored(const OdbDb& h, rust::Str bterm) { auto* p = gen_bterm(h, bterm); return p ? p->isMirrored() : false; }
