// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/generate-bindings.py from docs/derived-core-schema.json -- DO NOT EDIT.
//! Third cxx bridge: machine-generated SETTERS (the L2/write governance surface).
//! Gated behind the `gen-write` feature — absent from the default read-only build.

#[cxx::bridge]
mod ffi_gen_write {
    unsafe extern "C++" {
        include!("generated_write.h");
        type OdbDb = crate::ffi::OdbDb;
        fn block_clear_global_connect(db: &OdbDb) -> Result<()>;
        fn block_set_def_units(db: &OdbDb, units: i32) -> Result<()>;
        fn block_set_corner_name_list(db: &OdbDb, name_list: &str) -> Result<()>;
        fn block_set_corner_count(db: &OdbDb, corner_cnt: i32, ext_db_cnt: i32, name_list: &str) -> Result<()>;
        fn block_set_min_routing_layer(db: &OdbDb, min_routing_layer: i32) -> Result<()>;
        fn block_set_max_routing_layer(db: &OdbDb, max_routing_layer: i32) -> Result<()>;
        fn block_set_min_layer_for_clock(db: &OdbDb, min_layer_for_clock: i32) -> Result<()>;
        fn block_set_max_layer_for_clock(db: &OdbDb, max_layer_for_clock: i32) -> Result<()>;
        fn block_clear(db: &OdbDb) -> Result<()>;
        fn block_set_driving_itermsfor_nets(db: &OdbDb) -> Result<()>;
        fn block_clear_user_inst_flags(db: &OdbDb) -> Result<()>;
        fn inst_set_origin(db: &OdbDb, inst: &str, x: i32, y: i32) -> Result<()>;
        fn inst_set_orient(db: &OdbDb, inst: &str, orient: &str) -> Result<()>;
        fn inst_set_location(db: &OdbDb, inst: &str, x: i32, y: i32) -> Result<()>;
        fn inst_set_location_orient(db: &OdbDb, inst: &str, orient: &str) -> Result<()>;
        fn inst_set_placement_status(db: &OdbDb, inst: &str, status: &str) -> Result<()>;
        fn inst_set_eco_create(db: &OdbDb, inst: &str, v: bool) -> Result<()>;
        fn inst_set_eco_destroy(db: &OdbDb, inst: &str, v: bool) -> Result<()>;
        fn inst_set_eco_modify(db: &OdbDb, inst: &str, v: bool) -> Result<()>;
        fn inst_set_user_flag1(db: &OdbDb, inst: &str) -> Result<()>;
        fn inst_clear_user_flag1(db: &OdbDb, inst: &str) -> Result<()>;
        fn inst_set_user_flag2(db: &OdbDb, inst: &str) -> Result<()>;
        fn inst_clear_user_flag2(db: &OdbDb, inst: &str) -> Result<()>;
        fn inst_set_user_flag3(db: &OdbDb, inst: &str) -> Result<()>;
        fn inst_clear_user_flag3(db: &OdbDb, inst: &str) -> Result<()>;
        fn inst_set_do_not_touch(db: &OdbDb, inst: &str, v: bool) -> Result<()>;
        fn inst_set_halo(db: &OdbDb, inst: &str, left: i32, bottom: i32, right: i32, top: i32, is_soft: bool) -> Result<()>;
        fn inst_set_weight(db: &OdbDb, inst: &str, weight: i32) -> Result<()>;
        fn inst_set_source_type(db: &OdbDb, inst: &str, a0: &str) -> Result<()>;
        fn inst_set_pin_access_idx(db: &OdbDb, inst: &str, idx: u32) -> Result<()>;
        fn net_set_r_c_disconnected(db: &OdbDb, net: &str, value: bool) -> Result<()>;
        fn net_set_weight(db: &OdbDb, net: &str, weight: i32) -> Result<()>;
        fn net_set_source_type(db: &OdbDb, net: &str, a0: &str) -> Result<()>;
        fn net_set_x_talk_class(db: &OdbDb, net: &str, value: i32) -> Result<()>;
        fn net_set_fixed_bump(db: &OdbDb, net: &str, value: bool) -> Result<()>;
        fn net_set_wire_type(db: &OdbDb, net: &str, wire_type: &str) -> Result<()>;
        fn net_set_sig_type(db: &OdbDb, net: &str, sig_type: &str) -> Result<()>;
        fn net_set_mark(db: &OdbDb, net: &str, value: bool) -> Result<()>;
        fn net_set_mark_1(db: &OdbDb, net: &str, value: bool) -> Result<()>;
        fn net_set_select(db: &OdbDb, net: &str, value: bool) -> Result<()>;
        fn net_set_wire_ordered(db: &OdbDb, net: &str, value: bool) -> Result<()>;
        fn net_set_disconnected(db: &OdbDb, net: &str, value: bool) -> Result<()>;
        fn net_set_wire_altered(db: &OdbDb, net: &str, value: bool) -> Result<()>;
        fn net_set_r_cgraph(db: &OdbDb, net: &str, value: bool) -> Result<()>;
        fn net_set_extracted(db: &OdbDb, net: &str, value: bool) -> Result<()>;
        fn net_set_spef(db: &OdbDb, net: &str, value: bool) -> Result<()>;
        fn net_set_do_not_touch(db: &OdbDb, net: &str, v: bool) -> Result<()>;
        fn net_set_special(db: &OdbDb, net: &str) -> Result<()>;
        fn net_clear_special(db: &OdbDb, net: &str) -> Result<()>;
        fn net_set_i_oflag(db: &OdbDb, net: &str) -> Result<()>;
        fn net_set_wild_connected(db: &OdbDb, net: &str) -> Result<()>;
        fn net_clear_wild_connected(db: &OdbDb, net: &str) -> Result<()>;
        fn net_set_gndc_calib_factor(db: &OdbDb, net: &str, gndc_calib: f32) -> Result<()>;
        fn net_set_cc_calib_factor(db: &OdbDb, net: &str, cc_calib: f32) -> Result<()>;
        fn net_set_cc_adjust_factor(db: &OdbDb, net: &str, factor: f32) -> Result<()>;
        fn net_set_cc_adjust_order(db: &OdbDb, net: &str, order: u32) -> Result<()>;
        fn net_set_db_cc(db: &OdbDb, net: &str, cap: f32) -> Result<()>;
        fn net_set_ref_cc(db: &OdbDb, net: &str, cap: f32) -> Result<()>;
        fn net_set_cc_match_ratio(db: &OdbDb, net: &str, ratio: f32) -> Result<()>;
        fn net_set1st_r_seg_id(db: &OdbDb, net: &str, rseg_id: u32) -> Result<()>;
        fn net_set1st_cap_node_id(db: &OdbDb, net: &str, capn_id: u32) -> Result<()>;
        fn net_set_term_ext_ids(db: &OdbDb, net: &str, cap_id: i32) -> Result<()>;
        fn net_clear_guides(db: &OdbDb, net: &str) -> Result<()>;
        fn net_clear_tracks(db: &OdbDb, net: &str) -> Result<()>;
        fn net_set_jumpers(db: &OdbDb, net: &str, has_jumpers: bool) -> Result<()>;
        fn bterm_set_sig_type(db: &OdbDb, bterm: &str, a0: &str) -> Result<()>;
        fn bterm_set_io_type(db: &OdbDb, bterm: &str, a0: &str) -> Result<()>;
        fn bterm_set_spef_mark(db: &OdbDb, bterm: &str, v: u32) -> Result<()>;
        fn bterm_set_mark(db: &OdbDb, bterm: &str, v: u32) -> Result<()>;
        fn bterm_set_ext_id(db: &OdbDb, bterm: &str, v: u32) -> Result<()>;
        fn bterm_set_special(db: &OdbDb, bterm: &str) -> Result<()>;
        fn master_set_origin(db: &OdbDb, master: &str, x: i32, y: i32) -> Result<()>;
        fn master_set_width(db: &OdbDb, master: &str, width: u32) -> Result<()>;
        fn master_set_height(db: &OdbDb, master: &str, height: u32) -> Result<()>;
        fn master_set_backside_bridge(db: &OdbDb, master: &str, is_bridge: bool) -> Result<()>;
        fn master_set_symmetry_x(db: &OdbDb, master: &str) -> Result<()>;
        fn master_set_symmetry_y(db: &OdbDb, master: &str) -> Result<()>;
        fn master_set_symmetry_r90(db: &OdbDb, master: &str) -> Result<()>;
        fn master_set_frozen(db: &OdbDb, master: &str) -> Result<()>;
        fn master_set_sequential(db: &OdbDb, master: &str, v: bool) -> Result<()>;
        fn master_set_mark(db: &OdbDb, master: &str, mark: u32) -> Result<()>;
        fn master_set_special_power(db: &OdbDb, master: &str, v: bool) -> Result<()>;
        fn master_clear_pin_access(db: &OdbDb, master: &str, pin_access_idx: i32) -> Result<()>;
        fn iterm_set_spef(db: &OdbDb, inst: &str, pin: &str, v: u32) -> Result<()>;
        fn iterm_set_ext_id(db: &OdbDb, inst: &str, pin: &str, v: u32) -> Result<()>;
        fn iterm_set_special(db: &OdbDb, inst: &str, pin: &str) -> Result<()>;
        fn iterm_clear_special(db: &OdbDb, inst: &str, pin: &str) -> Result<()>;
        fn iterm_set_clocked(db: &OdbDb, inst: &str, pin: &str, v: bool) -> Result<()>;
        fn iterm_set_mark(db: &OdbDb, inst: &str, pin: &str, v: u32) -> Result<()>;
        fn iterm_set_connected(db: &OdbDb, inst: &str, pin: &str) -> Result<()>;
        fn iterm_clear_connected(db: &OdbDb, inst: &str, pin: &str) -> Result<()>;
        fn iterm_clear_pref_access_points(db: &OdbDb, inst: &str, pin: &str) -> Result<()>;
        fn mterm_set_sig_type(db: &OdbDb, master: &str, term: &str, a0: &str) -> Result<()>;
        fn mterm_set_mark(db: &OdbDb, master: &str, term: &str, v: u32) -> Result<()>;
        fn layer_set_wrong_way_width(db: &OdbDb, layer: &str, wrong_way_width: u32) -> Result<()>;
        fn layer_set_wrong_way_min_width(db: &OdbDb, layer: &str, wrong_way_min_width: u32) -> Result<()>;
        fn layer_set_layer_adjustment(db: &OdbDb, layer: &str, layer_adjustment: f32) -> Result<()>;
        fn layer_set_rect_only(db: &OdbDb, layer: &str, rect_only: bool) -> Result<()>;
        fn layer_set_right_way_on_grid_only(db: &OdbDb, layer: &str, right_way_on_grid_only: bool) -> Result<()>;
        fn layer_set_right_way_on_grid_only_check_mask(db: &OdbDb, layer: &str, right_way_on_grid_only_check_mask: bool) -> Result<()>;
        fn layer_set_rect_only_except_non_core_pins(db: &OdbDb, layer: &str, rect_only_except_non_core_pins: bool) -> Result<()>;
        fn layer_set_backside(db: &OdbDb, layer: &str, is_backside: bool) -> Result<()>;
        fn layer_set_alias(db: &OdbDb, layer: &str, alias: &str) -> Result<()>;
        fn layer_set_width(db: &OdbDb, layer: &str, width: i32) -> Result<()>;
        fn layer_set_spacing(db: &OdbDb, layer: &str, spacing: i32) -> Result<()>;
        fn layer_set_num_masks(db: &OdbDb, layer: &str, number: u32) -> Result<()>;
        fn layer_set_pitch(db: &OdbDb, layer: &str, pitch: i32) -> Result<()>;
        fn layer_set_pitch_x_y(db: &OdbDb, layer: &str, pitch_x: i32, pitch_y: i32) -> Result<()>;
        fn layer_set_first_last_pitch(db: &OdbDb, layer: &str, first_last_pitch: i32) -> Result<()>;
        fn layer_set_offset(db: &OdbDb, layer: &str, pitch: i32) -> Result<()>;
        fn layer_set_offset_x_y(db: &OdbDb, layer: &str, pitch_x: i32, pitch_y: i32) -> Result<()>;
        fn layer_set_thickness(db: &OdbDb, layer: &str, thickness: u32) -> Result<()>;
        fn layer_set_area(db: &OdbDb, layer: &str, area: i64) -> Result<()>;
        fn layer_set_max_width(db: &OdbDb, layer: &str, max_width: u32) -> Result<()>;
        fn layer_set_min_width(db: &OdbDb, layer: &str, max_width: u32) -> Result<()>;
        fn layer_set_min_step(db: &OdbDb, layer: &str, min_step: u32) -> Result<()>;
        fn layer_set_min_step_max_length(db: &OdbDb, layer: &str, length: u32) -> Result<()>;
        fn layer_set_min_step_max_edges(db: &OdbDb, layer: &str, edges: u32) -> Result<()>;
        fn layer_set_resistance(db: &OdbDb, layer: &str, res: f64) -> Result<()>;
        fn layer_set_capacitance(db: &OdbDb, layer: &str, cap: f64) -> Result<()>;
        fn layer_set_edge_capacitance(db: &OdbDb, layer: &str, cap: f64) -> Result<()>;
        fn layer_set_wire_extension(db: &OdbDb, layer: &str, ext: u32) -> Result<()>;
        fn via_set_pattern(db: &OdbDb, via: &str, pattern: &str) -> Result<()>;
        fn techvia_set_default(db: &OdbDb, via: &str) -> Result<()>;
        fn techvia_set_top_of_stack(db: &OdbDb, via: &str) -> Result<()>;
        fn techvia_set_resistance(db: &OdbDb, via: &str, res: f64) -> Result<()>;
        fn techvia_set_pattern(db: &OdbDb, via: &str, pattern: &str) -> Result<()>;
        fn ndr_set_hard_spacing(db: &OdbDb, rule: &str, value: bool) -> Result<()>;
        fn site_set_width(db: &OdbDb, site: &str, width: i32) -> Result<()>;
        fn site_set_height(db: &OdbDb, site: &str, height: i32) -> Result<()>;
        fn site_set_symmetry_x(db: &OdbDb, site: &str) -> Result<()>;
        fn site_set_symmetry_y(db: &OdbDb, site: &str) -> Result<()>;
        fn site_set_symmetry_r90(db: &OdbDb, site: &str) -> Result<()>;
        fn obs_set_slot_obstruction(db: &OdbDb, idx: usize) -> Result<()>;
        fn obs_set_fill_obstruction(db: &OdbDb, idx: usize) -> Result<()>;
        fn obs_set_except_p_g_nets_obstruction(db: &OdbDb, idx: usize) -> Result<()>;
        fn obs_set_pushed_down(db: &OdbDb, idx: usize) -> Result<()>;
        fn obs_set_effective_width(db: &OdbDb, idx: usize, w: i32) -> Result<()>;
        fn obs_set_min_spacing(db: &OdbDb, idx: usize, w: i32) -> Result<()>;
        fn obs_set_is_system_reserved(db: &OdbDb, idx: usize, is_system_reserved: bool) -> Result<()>;
        fn swire_set_wire_type(db: &OdbDb, net: &str, idx: usize, a0: &str) -> Result<()>;
        fn wire_set_property(db: &OdbDb, net: &str, jid: i32, property: i32) -> Result<()>;
        fn box_set_soft(db: &OdbDb, idx: usize, value: bool) -> Result<()>;
        fn box_set_layer_mask(db: &OdbDb, idx: usize, mask: u32) -> Result<()>;
        fn region_set_invalid(db: &OdbDb, region: &str, v: bool) -> Result<()>;
        fn blockage_set_pushed_down(db: &OdbDb, idx: usize) -> Result<()>;
        fn blockage_set_soft(db: &OdbDb, idx: usize) -> Result<()>;
        fn blockage_set_is_system_reserved(db: &OdbDb, idx: usize, is_system_reserved: bool) -> Result<()>;
        fn blockage_set_max_density(db: &OdbDb, idx: usize, max_density: f32) -> Result<()>;
        fn marker_cat_set_description(db: &OdbDb, category: &str, description: &str) -> Result<()>;
        fn marker_cat_set_source(db: &OdbDb, category: &str, source: &str) -> Result<()>;
        fn marker_cat_set_max_markers(db: &OdbDb, category: &str, max_markers: i32) -> Result<()>;
        fn marker_set_comment(db: &OdbDb, category: &str, idx: usize, comment: &str) -> Result<()>;
        fn marker_set_line_number(db: &OdbDb, category: &str, idx: usize, line_number: i32) -> Result<()>;
        fn marker_set_visited(db: &OdbDb, category: &str, idx: usize, visited: bool) -> Result<()>;
        fn marker_set_visible(db: &OdbDb, category: &str, idx: usize, visible: bool) -> Result<()>;
        fn marker_set_waived(db: &OdbDb, category: &str, idx: usize, waived: bool) -> Result<()>;
    }
}

pub use ffi_gen_write::{
    block_clear,
    block_clear_global_connect,
    block_clear_user_inst_flags,
    block_set_corner_count,
    block_set_corner_name_list,
    block_set_def_units,
    block_set_driving_itermsfor_nets,
    block_set_max_layer_for_clock,
    block_set_max_routing_layer,
    block_set_min_layer_for_clock,
    block_set_min_routing_layer,
    blockage_set_is_system_reserved,
    blockage_set_max_density,
    blockage_set_pushed_down,
    blockage_set_soft,
    box_set_layer_mask,
    box_set_soft,
    bterm_set_ext_id,
    bterm_set_io_type,
    bterm_set_mark,
    bterm_set_sig_type,
    bterm_set_special,
    bterm_set_spef_mark,
    inst_clear_user_flag1,
    inst_clear_user_flag2,
    inst_clear_user_flag3,
    inst_set_do_not_touch,
    inst_set_eco_create,
    inst_set_eco_destroy,
    inst_set_eco_modify,
    inst_set_halo,
    inst_set_location,
    inst_set_location_orient,
    inst_set_orient,
    inst_set_origin,
    inst_set_pin_access_idx,
    inst_set_placement_status,
    inst_set_source_type,
    inst_set_user_flag1,
    inst_set_user_flag2,
    inst_set_user_flag3,
    inst_set_weight,
    iterm_clear_connected,
    iterm_clear_pref_access_points,
    iterm_clear_special,
    iterm_set_clocked,
    iterm_set_connected,
    iterm_set_ext_id,
    iterm_set_mark,
    iterm_set_special,
    iterm_set_spef,
    layer_set_alias,
    layer_set_area,
    layer_set_backside,
    layer_set_capacitance,
    layer_set_edge_capacitance,
    layer_set_first_last_pitch,
    layer_set_layer_adjustment,
    layer_set_max_width,
    layer_set_min_step,
    layer_set_min_step_max_edges,
    layer_set_min_step_max_length,
    layer_set_min_width,
    layer_set_num_masks,
    layer_set_offset,
    layer_set_offset_x_y,
    layer_set_pitch,
    layer_set_pitch_x_y,
    layer_set_rect_only,
    layer_set_rect_only_except_non_core_pins,
    layer_set_resistance,
    layer_set_right_way_on_grid_only,
    layer_set_right_way_on_grid_only_check_mask,
    layer_set_spacing,
    layer_set_thickness,
    layer_set_width,
    layer_set_wire_extension,
    layer_set_wrong_way_min_width,
    layer_set_wrong_way_width,
    marker_cat_set_description,
    marker_cat_set_max_markers,
    marker_cat_set_source,
    marker_set_comment,
    marker_set_line_number,
    marker_set_visible,
    marker_set_visited,
    marker_set_waived,
    master_clear_pin_access,
    master_set_backside_bridge,
    master_set_frozen,
    master_set_height,
    master_set_mark,
    master_set_origin,
    master_set_sequential,
    master_set_special_power,
    master_set_symmetry_r90,
    master_set_symmetry_x,
    master_set_symmetry_y,
    master_set_width,
    mterm_set_mark,
    mterm_set_sig_type,
    ndr_set_hard_spacing,
    net_clear_guides,
    net_clear_special,
    net_clear_tracks,
    net_clear_wild_connected,
    net_set1st_cap_node_id,
    net_set1st_r_seg_id,
    net_set_cc_adjust_factor,
    net_set_cc_adjust_order,
    net_set_cc_calib_factor,
    net_set_cc_match_ratio,
    net_set_db_cc,
    net_set_disconnected,
    net_set_do_not_touch,
    net_set_extracted,
    net_set_fixed_bump,
    net_set_gndc_calib_factor,
    net_set_i_oflag,
    net_set_jumpers,
    net_set_mark,
    net_set_mark_1,
    net_set_r_c_disconnected,
    net_set_r_cgraph,
    net_set_ref_cc,
    net_set_select,
    net_set_sig_type,
    net_set_source_type,
    net_set_special,
    net_set_spef,
    net_set_term_ext_ids,
    net_set_weight,
    net_set_wild_connected,
    net_set_wire_altered,
    net_set_wire_ordered,
    net_set_wire_type,
    net_set_x_talk_class,
    obs_set_effective_width,
    obs_set_except_p_g_nets_obstruction,
    obs_set_fill_obstruction,
    obs_set_is_system_reserved,
    obs_set_min_spacing,
    obs_set_pushed_down,
    obs_set_slot_obstruction,
    region_set_invalid,
    site_set_height,
    site_set_symmetry_r90,
    site_set_symmetry_x,
    site_set_symmetry_y,
    site_set_width,
    swire_set_wire_type,
    techvia_set_default,
    techvia_set_pattern,
    techvia_set_resistance,
    techvia_set_top_of_stack,
    via_set_pattern,
    wire_set_property,
};
