// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/generate-bindings.py from docs/derived-core-schema.json -- DO NOT EDIT.
//! Second cxx bridge: machine-generated read accessors for core odb classes.
//! Shares the opaque `OdbDb` handle with the hand-written `ffi` bridge in lib.rs.

#[cxx::bridge]
mod ffi_gen {
    unsafe extern "C++" {
        include!("generated.h");
        type OdbDb = crate::ffi::OdbDb;
        fn block_get_name(db: &OdbDb) -> String;
        fn block_get_const_name(db: &OdbDb) -> String;
        fn block_get_tech(db: &OdbDb) -> String;
        fn block_get_parent(db: &OdbDb) -> String;
        fn block_get_parent_inst(db: &OdbDb) -> String;
        fn num_block_get_children(db: &OdbDb) -> usize;
        fn nth_block_get_children(db: &OdbDb, i: usize) -> String;
        fn num_block_get_b_terms(db: &OdbDb) -> usize;
        fn nth_block_get_b_terms(db: &OdbDb, i: usize) -> String;
        fn num_block_get_i_terms(db: &OdbDb) -> usize;
        fn nth_block_get_i_terms(db: &OdbDb, i: usize) -> String;
        fn num_block_get_insts(db: &OdbDb) -> usize;
        fn nth_block_get_insts(db: &OdbDb, i: usize) -> String;
        fn num_block_get_mod_nets(db: &OdbDb) -> usize;
        fn nth_block_get_mod_nets(db: &OdbDb, i: usize) -> String;
        fn num_block_get_nets(db: &OdbDb) -> usize;
        fn nth_block_get_nets(db: &OdbDb, i: usize) -> String;
        fn num_block_get_vias(db: &OdbDb) -> usize;
        fn nth_block_get_vias(db: &OdbDb, i: usize) -> String;
        fn block_get_def_units(db: &OdbDb) -> i32;
        fn block_get_db_units_per_micron(db: &OdbDb) -> i32;
        fn block_get_corner_count(db: &OdbDb) -> i32;
        fn block_get_corners_per_block(db: &OdbDb) -> i32;
        fn block_get_ext_db_count(db: &OdbDb) -> i32;
        fn block_get_corner_name_list(db: &OdbDb) -> String;
        fn num_block_get_rows(db: &OdbDb) -> usize;
        fn nth_block_get_rows(db: &OdbDb, i: usize) -> String;
        fn block_get_min_routing_layer(db: &OdbDb) -> i32;
        fn block_get_max_routing_layer(db: &OdbDb) -> i32;
        fn block_get_min_layer_for_clock(db: &OdbDb) -> i32;
        fn block_get_max_layer_for_clock(db: &OdbDb) -> i32;
        fn block_get_g_cell_tile_size(db: &OdbDb) -> i32;
        fn num_block_get_regions(db: &OdbDb) -> usize;
        fn nth_block_get_regions(db: &OdbDb, i: usize) -> String;
        fn num_block_get_non_default_rules(db: &OdbDb) -> usize;
        fn nth_block_get_non_default_rules(db: &OdbDb, i: usize) -> String;
        fn inst_get_name(db: &OdbDb, inst: &str) -> String;
        fn inst_get_const_name(db: &OdbDb, inst: &str) -> String;
        fn inst_get_orient(db: &OdbDb, inst: &str) -> String;
        fn inst_get_placement_status(db: &OdbDb, inst: &str) -> String;
        fn inst_is_fixed(db: &OdbDb, inst: &str) -> bool;
        fn inst_is_placed(db: &OdbDb, inst: &str) -> bool;
        fn inst_get_eco_create(db: &OdbDb, inst: &str) -> bool;
        fn inst_get_eco_destroy(db: &OdbDb, inst: &str) -> bool;
        fn inst_get_eco_modify(db: &OdbDb, inst: &str) -> bool;
        fn inst_get_user_flag1(db: &OdbDb, inst: &str) -> bool;
        fn inst_get_user_flag2(db: &OdbDb, inst: &str) -> bool;
        fn inst_get_user_flag3(db: &OdbDb, inst: &str) -> bool;
        fn inst_is_do_not_touch(db: &OdbDb, inst: &str) -> bool;
        fn inst_get_block(db: &OdbDb, inst: &str) -> String;
        fn inst_get_master(db: &OdbDb, inst: &str) -> String;
        fn num_inst_get_i_terms(db: &OdbDb, inst: &str) -> usize;
        fn nth_inst_get_i_terms(db: &OdbDb, inst: &str, i: usize) -> String;
        fn inst_get_first_input(db: &OdbDb, inst: &str) -> String;
        fn inst_get_first_output(db: &OdbDb, inst: &str) -> String;
        fn inst_get_region(db: &OdbDb, inst: &str) -> String;
        fn inst_get_child(db: &OdbDb, inst: &str) -> String;
        fn inst_get_parent(db: &OdbDb, inst: &str) -> String;
        fn num_inst_get_children(db: &OdbDb, inst: &str) -> usize;
        fn nth_inst_get_children(db: &OdbDb, inst: &str, i: usize) -> String;
        fn inst_is_hierarchical(db: &OdbDb, inst: &str) -> bool;
        fn inst_is_physical_only(db: &OdbDb, inst: &str) -> bool;
        fn inst_get_weight(db: &OdbDb, inst: &str) -> i32;
        fn inst_get_source_type(db: &OdbDb, inst: &str) -> String;
        fn inst_is_block(db: &OdbDb, inst: &str) -> bool;
        fn inst_is_core(db: &OdbDb, inst: &str) -> bool;
        fn inst_is_pad(db: &OdbDb, inst: &str) -> bool;
        fn inst_is_end_cap(db: &OdbDb, inst: &str) -> bool;
        fn inst_get_pin_access_idx(db: &OdbDb, inst: &str) -> u32;
        fn net_get_name(db: &OdbDb, net: &str) -> String;
        fn net_get_const_name(db: &OdbDb, net: &str) -> String;
        fn net_is_r_c_disconnected(db: &OdbDb, net: &str) -> bool;
        fn net_get_weight(db: &OdbDb, net: &str) -> i32;
        fn net_get_source_type(db: &OdbDb, net: &str) -> String;
        fn net_get_x_talk_class(db: &OdbDb, net: &str) -> i32;
        fn net_get_driving_i_term(db: &OdbDb, net: &str) -> String;
        fn net_has_fixed_bump(db: &OdbDb, net: &str) -> bool;
        fn net_get_wire_type(db: &OdbDb, net: &str) -> String;
        fn net_get_sig_type(db: &OdbDb, net: &str) -> String;
        fn net_is_marked(db: &OdbDb, net: &str) -> bool;
        fn net_is_mark_1ed(db: &OdbDb, net: &str) -> bool;
        fn net_is_select(db: &OdbDb, net: &str) -> bool;
        fn net_is_wire_ordered(db: &OdbDb, net: &str) -> bool;
        fn net_is_disconnected(db: &OdbDb, net: &str) -> bool;
        fn net_is_wire_altered(db: &OdbDb, net: &str) -> bool;
        fn net_is_r_cgraph(db: &OdbDb, net: &str) -> bool;
        fn net_is_extracted(db: &OdbDb, net: &str) -> bool;
        fn net_is_spef(db: &OdbDb, net: &str) -> bool;
        fn net_is_do_not_touch(db: &OdbDb, net: &str) -> bool;
        fn net_get_block(db: &OdbDb, net: &str) -> String;
        fn num_net_get_i_terms(db: &OdbDb, net: &str) -> usize;
        fn nth_net_get_i_terms(db: &OdbDb, net: &str, i: usize) -> String;
        fn net_get1st_i_term(db: &OdbDb, net: &str) -> String;
        fn net_get_first_driver_inst(db: &OdbDb, net: &str) -> String;
        fn net_get_first_output(db: &OdbDb, net: &str) -> String;
        fn num_net_get_b_terms(db: &OdbDb, net: &str) -> usize;
        fn nth_net_get_b_terms(db: &OdbDb, net: &str, i: usize) -> String;
        fn net_get1st_b_term(db: &OdbDb, net: &str) -> String;
        fn net_is_connected_by_abutment(db: &OdbDb, net: &str) -> bool;
        fn net_is_i_o(db: &OdbDb, net: &str) -> bool;
        fn net_is_wild_connected(db: &OdbDb, net: &str) -> bool;
        fn net_get_gndc_calib_factor(db: &OdbDb, net: &str) -> f32;
        fn net_get_cc_calib_factor(db: &OdbDb, net: &str) -> f32;
        fn net_get_cc_adjust_factor(db: &OdbDb, net: &str) -> f32;
        fn net_get_cc_adjust_order(db: &OdbDb, net: &str) -> u32;
        fn net_get_db_cc(db: &OdbDb, net: &str) -> f32;
        fn net_get_ref_cc(db: &OdbDb, net: &str) -> f32;
        fn net_get_cc_match_ratio(db: &OdbDb, net: &str) -> f32;
        fn net_get1st_r_seg_id(db: &OdbDb, net: &str) -> u32;
        fn net_get1st_cap_node_id(db: &OdbDb, net: &str) -> u32;
        fn net_get_r_seg_count(db: &OdbDb, net: &str) -> u32;
        fn net_max_internal_cap_num(db: &OdbDb, net: &str) -> u32;
        fn net_get_cap_node_count(db: &OdbDb, net: &str) -> u32;
        fn net_get_cc_count(db: &OdbDb, net: &str) -> u32;
        fn net_get_non_default_rule(db: &OdbDb, net: &str) -> String;
        fn net_get_term_count(db: &OdbDb, net: &str) -> u32;
        fn net_get_i_term_count(db: &OdbDb, net: &str) -> u32;
        fn net_get_b_term_count(db: &OdbDb, net: &str) -> u32;
        fn net_has_jumpers(db: &OdbDb, net: &str) -> bool;
        fn net_find_mod_net_in_highest_hier(db: &OdbDb, net: &str) -> String;
        fn bterm_get_name(db: &OdbDb, bterm: &str) -> String;
        fn bterm_get_const_name(db: &OdbDb, bterm: &str) -> String;
        fn bterm_get_sig_type(db: &OdbDb, bterm: &str) -> String;
        fn bterm_get_io_type(db: &OdbDb, bterm: &str) -> String;
        fn bterm_is_set_spef_mark(db: &OdbDb, bterm: &str) -> bool;
        fn bterm_is_set_mark(db: &OdbDb, bterm: &str) -> bool;
        fn bterm_get_ext_id(db: &OdbDb, bterm: &str) -> u32;
        fn bterm_is_special(db: &OdbDb, bterm: &str) -> bool;
        fn bterm_get_net(db: &OdbDb, bterm: &str) -> String;
        fn bterm_get_mod_net(db: &OdbDb, bterm: &str) -> String;
        fn bterm_get_block(db: &OdbDb, bterm: &str) -> String;
        fn bterm_get_i_term(db: &OdbDb, bterm: &str) -> String;
        fn bterm_get_first_pin_placement_status(db: &OdbDb, bterm: &str) -> String;
        fn bterm_get_ground_pin(db: &OdbDb, bterm: &str) -> String;
        fn bterm_get_supply_pin(db: &OdbDb, bterm: &str) -> String;
        fn bterm_sta_vertex_id(db: &OdbDb, bterm: &str) -> u32;
        fn bterm_get_mirrored_b_term(db: &OdbDb, bterm: &str) -> String;
        fn bterm_has_mirrored_b_term(db: &OdbDb, bterm: &str) -> bool;
        fn bterm_is_mirrored(db: &OdbDb, bterm: &str) -> bool;
    }
}

pub use ffi_gen::{
    block_get_const_name,
    block_get_corner_count,
    block_get_corner_name_list,
    block_get_corners_per_block,
    block_get_db_units_per_micron,
    block_get_def_units,
    block_get_ext_db_count,
    block_get_g_cell_tile_size,
    block_get_max_layer_for_clock,
    block_get_max_routing_layer,
    block_get_min_layer_for_clock,
    block_get_min_routing_layer,
    block_get_name,
    block_get_parent,
    block_get_parent_inst,
    block_get_tech,
    bterm_get_block,
    bterm_get_const_name,
    bterm_get_ext_id,
    bterm_get_first_pin_placement_status,
    bterm_get_ground_pin,
    bterm_get_i_term,
    bterm_get_io_type,
    bterm_get_mirrored_b_term,
    bterm_get_mod_net,
    bterm_get_name,
    bterm_get_net,
    bterm_get_sig_type,
    bterm_get_supply_pin,
    bterm_has_mirrored_b_term,
    bterm_is_mirrored,
    bterm_is_set_mark,
    bterm_is_set_spef_mark,
    bterm_is_special,
    bterm_sta_vertex_id,
    inst_get_block,
    inst_get_child,
    inst_get_const_name,
    inst_get_eco_create,
    inst_get_eco_destroy,
    inst_get_eco_modify,
    inst_get_first_input,
    inst_get_first_output,
    inst_get_master,
    inst_get_name,
    inst_get_orient,
    inst_get_parent,
    inst_get_pin_access_idx,
    inst_get_placement_status,
    inst_get_region,
    inst_get_source_type,
    inst_get_user_flag1,
    inst_get_user_flag2,
    inst_get_user_flag3,
    inst_get_weight,
    inst_is_block,
    inst_is_core,
    inst_is_do_not_touch,
    inst_is_end_cap,
    inst_is_fixed,
    inst_is_hierarchical,
    inst_is_pad,
    inst_is_physical_only,
    inst_is_placed,
    net_find_mod_net_in_highest_hier,
    net_get1st_b_term,
    net_get1st_cap_node_id,
    net_get1st_i_term,
    net_get1st_r_seg_id,
    net_get_b_term_count,
    net_get_block,
    net_get_cap_node_count,
    net_get_cc_adjust_factor,
    net_get_cc_adjust_order,
    net_get_cc_calib_factor,
    net_get_cc_count,
    net_get_cc_match_ratio,
    net_get_const_name,
    net_get_db_cc,
    net_get_driving_i_term,
    net_get_first_driver_inst,
    net_get_first_output,
    net_get_gndc_calib_factor,
    net_get_i_term_count,
    net_get_name,
    net_get_non_default_rule,
    net_get_r_seg_count,
    net_get_ref_cc,
    net_get_sig_type,
    net_get_source_type,
    net_get_term_count,
    net_get_weight,
    net_get_wire_type,
    net_get_x_talk_class,
    net_has_fixed_bump,
    net_has_jumpers,
    net_is_connected_by_abutment,
    net_is_disconnected,
    net_is_do_not_touch,
    net_is_extracted,
    net_is_i_o,
    net_is_mark_1ed,
    net_is_marked,
    net_is_r_c_disconnected,
    net_is_r_cgraph,
    net_is_select,
    net_is_spef,
    net_is_wild_connected,
    net_is_wire_altered,
    net_is_wire_ordered,
    net_max_internal_cap_num,
    nth_block_get_b_terms,
    nth_block_get_children,
    nth_block_get_i_terms,
    nth_block_get_insts,
    nth_block_get_mod_nets,
    nth_block_get_nets,
    nth_block_get_non_default_rules,
    nth_block_get_regions,
    nth_block_get_rows,
    nth_block_get_vias,
    nth_inst_get_children,
    nth_inst_get_i_terms,
    nth_net_get_b_terms,
    nth_net_get_i_terms,
    num_block_get_b_terms,
    num_block_get_children,
    num_block_get_i_terms,
    num_block_get_insts,
    num_block_get_mod_nets,
    num_block_get_nets,
    num_block_get_non_default_rules,
    num_block_get_regions,
    num_block_get_rows,
    num_block_get_vias,
    num_inst_get_children,
    num_inst_get_i_terms,
    num_net_get_b_terms,
    num_net_get_i_terms,
};
