// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/generate-bindings.py from docs/derived-core-schema.json -- DO NOT EDIT.
//! Second cxx bridge: machine-generated read accessors for core odb classes.
//! Shares the opaque `OdbDb` handle with the hand-written `ffi` bridge in lib.rs.

#[cxx::bridge]
mod ffi_gen {
    unsafe extern "C++" {
        include!("generated.h");
        type OdbDb = crate::ffi::OdbDb;
        fn block_get_name(db: &OdbDb) -> String;
        fn block_get_const_name(db: &OdbDb) -> String;
        fn block_get_tech(db: &OdbDb) -> String;
        fn block_get_parent(db: &OdbDb) -> String;
        fn block_get_parent_inst(db: &OdbDb) -> String;
        fn num_block_get_children(db: &OdbDb) -> usize;
        fn nth_block_get_children(db: &OdbDb, i: usize) -> String;
        fn num_block_get_b_terms(db: &OdbDb) -> usize;
        fn nth_block_get_b_terms(db: &OdbDb, i: usize) -> String;
        fn num_block_get_i_terms(db: &OdbDb) -> usize;
        fn nth_block_get_i_terms(db: &OdbDb, i: usize) -> String;
        fn num_block_get_insts(db: &OdbDb) -> usize;
        fn nth_block_get_insts(db: &OdbDb, i: usize) -> String;
        fn num_block_get_mod_nets(db: &OdbDb) -> usize;
        fn nth_block_get_mod_nets(db: &OdbDb, i: usize) -> String;
        fn num_block_get_nets(db: &OdbDb) -> usize;
        fn nth_block_get_nets(db: &OdbDb, i: usize) -> String;
        fn num_block_get_vias(db: &OdbDb) -> usize;
        fn nth_block_get_vias(db: &OdbDb, i: usize) -> String;
        fn block_get_def_units(db: &OdbDb) -> i32;
        fn block_get_db_units_per_micron(db: &OdbDb) -> i32;
        fn block_get_corner_count(db: &OdbDb) -> i32;
        fn block_get_corners_per_block(db: &OdbDb) -> i32;
        fn block_get_ext_db_count(db: &OdbDb) -> i32;
        fn block_get_corner_name_list(db: &OdbDb) -> String;
        fn num_block_get_rows(db: &OdbDb) -> usize;
        fn nth_block_get_rows(db: &OdbDb, i: usize) -> String;
        fn block_get_min_routing_layer(db: &OdbDb) -> i32;
        fn block_get_max_routing_layer(db: &OdbDb) -> i32;
        fn block_get_min_layer_for_clock(db: &OdbDb) -> i32;
        fn block_get_max_layer_for_clock(db: &OdbDb) -> i32;
        fn block_get_g_cell_tile_size(db: &OdbDb) -> i32;
        fn num_block_get_regions(db: &OdbDb) -> usize;
        fn nth_block_get_regions(db: &OdbDb, i: usize) -> String;
        fn num_block_get_non_default_rules(db: &OdbDb) -> usize;
        fn nth_block_get_non_default_rules(db: &OdbDb, i: usize) -> String;
        fn inst_get_name(db: &OdbDb, inst: &str) -> String;
        fn inst_get_const_name(db: &OdbDb, inst: &str) -> String;
        fn inst_get_orient(db: &OdbDb, inst: &str) -> String;
        fn inst_get_placement_status(db: &OdbDb, inst: &str) -> String;
        fn inst_is_fixed(db: &OdbDb, inst: &str) -> bool;
        fn inst_is_placed(db: &OdbDb, inst: &str) -> bool;
        fn inst_get_eco_create(db: &OdbDb, inst: &str) -> bool;
        fn inst_get_eco_destroy(db: &OdbDb, inst: &str) -> bool;
        fn inst_get_eco_modify(db: &OdbDb, inst: &str) -> bool;
        fn inst_get_user_flag1(db: &OdbDb, inst: &str) -> bool;
        fn inst_get_user_flag2(db: &OdbDb, inst: &str) -> bool;
        fn inst_get_user_flag3(db: &OdbDb, inst: &str) -> bool;
        fn inst_is_do_not_touch(db: &OdbDb, inst: &str) -> bool;
        fn inst_get_block(db: &OdbDb, inst: &str) -> String;
        fn inst_get_master(db: &OdbDb, inst: &str) -> String;
        fn num_inst_get_i_terms(db: &OdbDb, inst: &str) -> usize;
        fn nth_inst_get_i_terms(db: &OdbDb, inst: &str, i: usize) -> String;
        fn inst_get_first_input(db: &OdbDb, inst: &str) -> String;
        fn inst_get_first_output(db: &OdbDb, inst: &str) -> String;
        fn inst_get_region(db: &OdbDb, inst: &str) -> String;
        fn inst_get_child(db: &OdbDb, inst: &str) -> String;
        fn inst_get_parent(db: &OdbDb, inst: &str) -> String;
        fn num_inst_get_children(db: &OdbDb, inst: &str) -> usize;
        fn nth_inst_get_children(db: &OdbDb, inst: &str, i: usize) -> String;
        fn inst_is_hierarchical(db: &OdbDb, inst: &str) -> bool;
        fn inst_is_physical_only(db: &OdbDb, inst: &str) -> bool;
        fn inst_get_weight(db: &OdbDb, inst: &str) -> i32;
        fn inst_get_source_type(db: &OdbDb, inst: &str) -> String;
        fn inst_is_block(db: &OdbDb, inst: &str) -> bool;
        fn inst_is_core(db: &OdbDb, inst: &str) -> bool;
        fn inst_is_pad(db: &OdbDb, inst: &str) -> bool;
        fn inst_is_end_cap(db: &OdbDb, inst: &str) -> bool;
        fn inst_get_pin_access_idx(db: &OdbDb, inst: &str) -> u32;
        fn net_get_name(db: &OdbDb, net: &str) -> String;
        fn net_get_const_name(db: &OdbDb, net: &str) -> String;
        fn net_is_r_c_disconnected(db: &OdbDb, net: &str) -> bool;
        fn net_get_weight(db: &OdbDb, net: &str) -> i32;
        fn net_get_source_type(db: &OdbDb, net: &str) -> String;
        fn net_get_x_talk_class(db: &OdbDb, net: &str) -> i32;
        fn net_get_driving_i_term(db: &OdbDb, net: &str) -> String;
        fn net_has_fixed_bump(db: &OdbDb, net: &str) -> bool;
        fn net_get_wire_type(db: &OdbDb, net: &str) -> String;
        fn net_get_sig_type(db: &OdbDb, net: &str) -> String;
        fn net_is_marked(db: &OdbDb, net: &str) -> bool;
        fn net_is_mark_1ed(db: &OdbDb, net: &str) -> bool;
        fn net_is_select(db: &OdbDb, net: &str) -> bool;
        fn net_is_wire_ordered(db: &OdbDb, net: &str) -> bool;
        fn net_is_disconnected(db: &OdbDb, net: &str) -> bool;
        fn net_is_wire_altered(db: &OdbDb, net: &str) -> bool;
        fn net_is_r_cgraph(db: &OdbDb, net: &str) -> bool;
        fn net_is_extracted(db: &OdbDb, net: &str) -> bool;
        fn net_is_spef(db: &OdbDb, net: &str) -> bool;
        fn net_is_do_not_touch(db: &OdbDb, net: &str) -> bool;
        fn net_get_block(db: &OdbDb, net: &str) -> String;
        fn num_net_get_i_terms(db: &OdbDb, net: &str) -> usize;
        fn nth_net_get_i_terms(db: &OdbDb, net: &str, i: usize) -> String;
        fn net_get1st_i_term(db: &OdbDb, net: &str) -> String;
        fn net_get_first_driver_inst(db: &OdbDb, net: &str) -> String;
        fn net_get_first_output(db: &OdbDb, net: &str) -> String;
        fn num_net_get_b_terms(db: &OdbDb, net: &str) -> usize;
        fn nth_net_get_b_terms(db: &OdbDb, net: &str, i: usize) -> String;
        fn net_get1st_b_term(db: &OdbDb, net: &str) -> String;
        fn net_is_connected_by_abutment(db: &OdbDb, net: &str) -> bool;
        fn net_is_i_o(db: &OdbDb, net: &str) -> bool;
        fn net_is_wild_connected(db: &OdbDb, net: &str) -> bool;
        fn net_get_gndc_calib_factor(db: &OdbDb, net: &str) -> f32;
        fn net_get_cc_calib_factor(db: &OdbDb, net: &str) -> f32;
        fn net_get_cc_adjust_factor(db: &OdbDb, net: &str) -> f32;
        fn net_get_cc_adjust_order(db: &OdbDb, net: &str) -> u32;
        fn net_get_db_cc(db: &OdbDb, net: &str) -> f32;
        fn net_get_ref_cc(db: &OdbDb, net: &str) -> f32;
        fn net_get_cc_match_ratio(db: &OdbDb, net: &str) -> f32;
        fn net_get1st_r_seg_id(db: &OdbDb, net: &str) -> u32;
        fn net_get1st_cap_node_id(db: &OdbDb, net: &str) -> u32;
        fn net_get_r_seg_count(db: &OdbDb, net: &str) -> u32;
        fn net_max_internal_cap_num(db: &OdbDb, net: &str) -> u32;
        fn net_get_cap_node_count(db: &OdbDb, net: &str) -> u32;
        fn net_get_cc_count(db: &OdbDb, net: &str) -> u32;
        fn net_get_non_default_rule(db: &OdbDb, net: &str) -> String;
        fn net_get_term_count(db: &OdbDb, net: &str) -> u32;
        fn net_get_i_term_count(db: &OdbDb, net: &str) -> u32;
        fn net_get_b_term_count(db: &OdbDb, net: &str) -> u32;
        fn net_has_jumpers(db: &OdbDb, net: &str) -> bool;
        fn net_find_mod_net_in_highest_hier(db: &OdbDb, net: &str) -> String;
        fn bterm_get_name(db: &OdbDb, bterm: &str) -> String;
        fn bterm_get_const_name(db: &OdbDb, bterm: &str) -> String;
        fn bterm_get_sig_type(db: &OdbDb, bterm: &str) -> String;
        fn bterm_get_io_type(db: &OdbDb, bterm: &str) -> String;
        fn bterm_is_set_spef_mark(db: &OdbDb, bterm: &str) -> bool;
        fn bterm_is_set_mark(db: &OdbDb, bterm: &str) -> bool;
        fn bterm_get_ext_id(db: &OdbDb, bterm: &str) -> u32;
        fn bterm_is_special(db: &OdbDb, bterm: &str) -> bool;
        fn bterm_get_net(db: &OdbDb, bterm: &str) -> String;
        fn bterm_get_mod_net(db: &OdbDb, bterm: &str) -> String;
        fn bterm_get_block(db: &OdbDb, bterm: &str) -> String;
        fn bterm_get_i_term(db: &OdbDb, bterm: &str) -> String;
        fn bterm_get_first_pin_placement_status(db: &OdbDb, bterm: &str) -> String;
        fn bterm_get_ground_pin(db: &OdbDb, bterm: &str) -> String;
        fn bterm_get_supply_pin(db: &OdbDb, bterm: &str) -> String;
        fn bterm_sta_vertex_id(db: &OdbDb, bterm: &str) -> u32;
        fn bterm_get_mirrored_b_term(db: &OdbDb, bterm: &str) -> String;
        fn bterm_has_mirrored_b_term(db: &OdbDb, bterm: &str) -> bool;
        fn bterm_is_mirrored(db: &OdbDb, bterm: &str) -> bool;
        fn master_get_name(db: &OdbDb, master: &str) -> String;
        fn master_get_const_name(db: &OdbDb, master: &str) -> String;
        fn master_get_width(db: &OdbDb, master: &str) -> u32;
        fn master_get_height(db: &OdbDb, master: &str) -> u32;
        fn master_is_filler(db: &OdbDb, master: &str) -> bool;
        fn master_is_block(db: &OdbDb, master: &str) -> bool;
        fn master_is_core(db: &OdbDb, master: &str) -> bool;
        fn master_is_pad(db: &OdbDb, master: &str) -> bool;
        fn master_is_end_cap(db: &OdbDb, master: &str) -> bool;
        fn master_is_cover(db: &OdbDb, master: &str) -> bool;
        fn master_is_core_auto_placeable(db: &OdbDb, master: &str) -> bool;
        fn master_is_backside_bridge(db: &OdbDb, master: &str) -> bool;
        fn master_get_l_e_q(db: &OdbDb, master: &str) -> String;
        fn master_get_e_e_q(db: &OdbDb, master: &str) -> String;
        fn master_get_symmetry_x(db: &OdbDb, master: &str) -> bool;
        fn master_get_symmetry_y(db: &OdbDb, master: &str) -> bool;
        fn master_get_symmetry_r90(db: &OdbDb, master: &str) -> bool;
        fn num_master_get_m_terms(db: &OdbDb, master: &str) -> usize;
        fn nth_master_get_m_terms(db: &OdbDb, master: &str, i: usize) -> String;
        fn master_get_lib(db: &OdbDb, master: &str) -> String;
        fn master_is_frozen(db: &OdbDb, master: &str) -> bool;
        fn master_is_sequential(db: &OdbDb, master: &str) -> bool;
        fn master_is_marked(db: &OdbDb, master: &str) -> u32;
        fn master_is_special_power(db: &OdbDb, master: &str) -> bool;
        fn master_get_m_term_count(db: &OdbDb, master: &str) -> i32;
        fn master_get_site(db: &OdbDb, master: &str) -> String;
        fn master_get_master_id(db: &OdbDb, master: &str) -> i32;
        fn iterm_get_inst(db: &OdbDb, inst: &str, pin: &str) -> String;
        fn iterm_get_net(db: &OdbDb, inst: &str, pin: &str) -> String;
        fn iterm_get_mod_net(db: &OdbDb, inst: &str, pin: &str) -> String;
        fn iterm_get_m_term(db: &OdbDb, inst: &str, pin: &str) -> String;
        fn iterm_get_block(db: &OdbDb, inst: &str, pin: &str) -> String;
        fn iterm_get_sig_type(db: &OdbDb, inst: &str, pin: &str) -> String;
        fn iterm_get_io_type(db: &OdbDb, inst: &str, pin: &str) -> String;
        fn iterm_is_spef(db: &OdbDb, inst: &str, pin: &str) -> bool;
        fn iterm_get_ext_id(db: &OdbDb, inst: &str, pin: &str) -> u32;
        fn iterm_is_special(db: &OdbDb, inst: &str, pin: &str) -> bool;
        fn iterm_is_clocked(db: &OdbDb, inst: &str, pin: &str) -> bool;
        fn iterm_is_set_mark(db: &OdbDb, inst: &str, pin: &str) -> bool;
        fn iterm_is_connected(db: &OdbDb, inst: &str, pin: &str) -> bool;
        fn iterm_get_b_term(db: &OdbDb, inst: &str, pin: &str) -> String;
        fn iterm_sta_vertex_id(db: &OdbDb, inst: &str, pin: &str) -> u32;
        fn mterm_get_name(db: &OdbDb, master: &str, term: &str) -> String;
        fn mterm_get_const_name(db: &OdbDb, master: &str, term: &str) -> String;
        fn mterm_get_sig_type(db: &OdbDb, master: &str, term: &str) -> String;
        fn mterm_get_io_type(db: &OdbDb, master: &str, term: &str) -> String;
        fn mterm_is_set_mark(db: &OdbDb, master: &str, term: &str) -> bool;
        fn mterm_get_master(db: &OdbDb, master: &str, term: &str) -> String;
        fn mterm_has_default_antenna_model(db: &OdbDb, master: &str, term: &str) -> bool;
        fn mterm_has_oxide2_antenna_model(db: &OdbDb, master: &str, term: &str) -> bool;
        fn mterm_get_index(db: &OdbDb, master: &str, term: &str) -> i32;
        fn layer_get_wrong_way_width(db: &OdbDb, layer: &str) -> u32;
        fn layer_get_wrong_way_min_width(db: &OdbDb, layer: &str) -> u32;
        fn layer_get_layer_adjustment(db: &OdbDb, layer: &str) -> f32;
        fn layer_is_rect_only(db: &OdbDb, layer: &str) -> bool;
        fn layer_is_right_way_on_grid_only(db: &OdbDb, layer: &str) -> bool;
        fn layer_is_right_way_on_grid_only_check_mask(db: &OdbDb, layer: &str) -> bool;
        fn layer_is_rect_only_except_non_core_pins(db: &OdbDb, layer: &str) -> bool;
        fn layer_get_lef58_type_string(db: &OdbDb, layer: &str) -> String;
        fn layer_is_backside(db: &OdbDb, layer: &str) -> bool;
        fn layer_get_name(db: &OdbDb, layer: &str) -> String;
        fn layer_get_const_name(db: &OdbDb, layer: &str) -> String;
        fn layer_has_alias(db: &OdbDb, layer: &str) -> bool;
        fn layer_get_alias(db: &OdbDb, layer: &str) -> String;
        fn layer_get_width(db: &OdbDb, layer: &str) -> u32;
        fn layer_get_spacing(db: &OdbDb, layer: &str) -> i32;
        fn layer_get_num_masks(db: &OdbDb, layer: &str) -> u32;
        fn layer_has_v55_spacing_rules(db: &OdbDb, layer: &str) -> bool;
        fn layer_has_two_widths_spacing_rules(db: &OdbDb, layer: &str) -> bool;
        fn layer_get_two_widths_spacing_table_num_widths(db: &OdbDb, layer: &str) -> u32;
        fn layer_has_default_antenna_rule(db: &OdbDb, layer: &str) -> bool;
        fn layer_has_oxide2_antenna_rule(db: &OdbDb, layer: &str) -> bool;
        fn layer_get_pitch(db: &OdbDb, layer: &str) -> i32;
        fn layer_get_pitch_x(db: &OdbDb, layer: &str) -> i32;
        fn layer_get_pitch_y(db: &OdbDb, layer: &str) -> i32;
        fn layer_get_first_last_pitch(db: &OdbDb, layer: &str) -> i32;
        fn layer_has_x_y_pitch(db: &OdbDb, layer: &str) -> bool;
        fn layer_get_offset(db: &OdbDb, layer: &str) -> i32;
        fn layer_get_offset_x(db: &OdbDb, layer: &str) -> i32;
        fn layer_get_offset_y(db: &OdbDb, layer: &str) -> i32;
        fn layer_has_x_y_offset(db: &OdbDb, layer: &str) -> bool;
        fn layer_has_area(db: &OdbDb, layer: &str) -> bool;
        fn layer_has_max_width(db: &OdbDb, layer: &str) -> bool;
        fn layer_get_max_width(db: &OdbDb, layer: &str) -> u32;
        fn layer_get_min_width(db: &OdbDb, layer: &str) -> u32;
        fn layer_has_min_step(db: &OdbDb, layer: &str) -> bool;
        fn layer_get_min_step(db: &OdbDb, layer: &str) -> u32;
        fn layer_has_min_step_max_length(db: &OdbDb, layer: &str) -> bool;
        fn layer_get_min_step_max_length(db: &OdbDb, layer: &str) -> u32;
        fn layer_has_min_step_max_edges(db: &OdbDb, layer: &str) -> bool;
        fn layer_get_min_step_max_edges(db: &OdbDb, layer: &str) -> u32;
        fn layer_has_protrusion(db: &OdbDb, layer: &str) -> bool;
        fn layer_get_protrusion_width(db: &OdbDb, layer: &str) -> u32;
        fn layer_get_protrusion_length(db: &OdbDb, layer: &str) -> u32;
        fn layer_get_protrusion_from_width(db: &OdbDb, layer: &str) -> u32;
        fn layer_get_resistance(db: &OdbDb, layer: &str) -> f64;
        fn layer_get_capacitance(db: &OdbDb, layer: &str) -> f64;
        fn layer_get_edge_capacitance(db: &OdbDb, layer: &str) -> f64;
        fn layer_get_wire_extension(db: &OdbDb, layer: &str) -> u32;
        fn layer_get_number(db: &OdbDb, layer: &str) -> i32;
        fn layer_get_routing_level(db: &OdbDb, layer: &str) -> i32;
        fn layer_get_lower_layer(db: &OdbDb, layer: &str) -> String;
        fn layer_get_upper_layer(db: &OdbDb, layer: &str) -> String;
        fn layer_get_tech(db: &OdbDb, layer: &str) -> String;
        fn layer_has_orth_spacing_table(db: &OdbDb, layer: &str) -> bool;
        fn row_get_name(db: &OdbDb, row: &str) -> String;
        fn row_get_const_name(db: &OdbDb, row: &str) -> String;
        fn row_get_site(db: &OdbDb, row: &str) -> String;
        fn row_get_orient(db: &OdbDb, row: &str) -> String;
        fn row_get_site_count(db: &OdbDb, row: &str) -> i32;
        fn row_get_spacing(db: &OdbDb, row: &str) -> i32;
        fn row_get_block(db: &OdbDb, row: &str) -> String;
        fn via_get_name(db: &OdbDb, via: &str) -> String;
        fn via_get_const_name(db: &OdbDb, via: &str) -> String;
        fn via_get_pattern(db: &OdbDb, via: &str) -> String;
        fn via_get_via_generate_rule(db: &OdbDb, via: &str) -> String;
        fn via_has_params(db: &OdbDb, via: &str) -> bool;
        fn via_get_block(db: &OdbDb, via: &str) -> String;
        fn via_get_top_layer(db: &OdbDb, via: &str) -> String;
        fn via_get_bottom_layer(db: &OdbDb, via: &str) -> String;
        fn via_is_via_rotated(db: &OdbDb, via: &str) -> bool;
        fn via_get_orient(db: &OdbDb, via: &str) -> String;
        fn via_get_tech_via(db: &OdbDb, via: &str) -> String;
        fn via_get_block_via(db: &OdbDb, via: &str) -> String;
        fn via_is_default(db: &OdbDb, via: &str) -> bool;
        fn techvia_get_name(db: &OdbDb, via: &str) -> String;
        fn techvia_get_const_name(db: &OdbDb, via: &str) -> String;
        fn techvia_is_default(db: &OdbDb, via: &str) -> bool;
        fn techvia_is_top_of_stack(db: &OdbDb, via: &str) -> bool;
        fn techvia_get_resistance(db: &OdbDb, via: &str) -> f64;
        fn techvia_get_pattern(db: &OdbDb, via: &str) -> String;
        fn techvia_get_via_generate_rule(db: &OdbDb, via: &str) -> String;
        fn techvia_has_params(db: &OdbDb, via: &str) -> bool;
        fn techvia_get_tech(db: &OdbDb, via: &str) -> String;
        fn techvia_get_top_layer(db: &OdbDb, via: &str) -> String;
        fn techvia_get_bottom_layer(db: &OdbDb, via: &str) -> String;
        fn techvia_get_non_default_rule(db: &OdbDb, via: &str) -> String;
        fn ndr_get_name(db: &OdbDb, rule: &str) -> String;
        fn ndr_get_const_name(db: &OdbDb, rule: &str) -> String;
        fn ndr_is_block_rule(db: &OdbDb, rule: &str) -> bool;
        fn ndr_get_hard_spacing(db: &OdbDb, rule: &str) -> bool;
        fn site_get_name(db: &OdbDb, site: &str) -> String;
        fn site_get_const_name(db: &OdbDb, site: &str) -> String;
        fn site_get_width(db: &OdbDb, site: &str) -> i32;
        fn site_get_height(db: &OdbDb, site: &str) -> i32;
        fn site_get_symmetry_x(db: &OdbDb, site: &str) -> bool;
        fn site_get_symmetry_y(db: &OdbDb, site: &str) -> bool;
        fn site_get_symmetry_r90(db: &OdbDb, site: &str) -> bool;
        fn site_has_row_pattern(db: &OdbDb, site: &str) -> bool;
        fn site_is_hybrid(db: &OdbDb, site: &str) -> bool;
        fn site_get_lib(db: &OdbDb, site: &str) -> String;
    }
}

pub use ffi_gen::{
    block_get_const_name,
    block_get_corner_count,
    block_get_corner_name_list,
    block_get_corners_per_block,
    block_get_db_units_per_micron,
    block_get_def_units,
    block_get_ext_db_count,
    block_get_g_cell_tile_size,
    block_get_max_layer_for_clock,
    block_get_max_routing_layer,
    block_get_min_layer_for_clock,
    block_get_min_routing_layer,
    block_get_name,
    block_get_parent,
    block_get_parent_inst,
    block_get_tech,
    bterm_get_block,
    bterm_get_const_name,
    bterm_get_ext_id,
    bterm_get_first_pin_placement_status,
    bterm_get_ground_pin,
    bterm_get_i_term,
    bterm_get_io_type,
    bterm_get_mirrored_b_term,
    bterm_get_mod_net,
    bterm_get_name,
    bterm_get_net,
    bterm_get_sig_type,
    bterm_get_supply_pin,
    bterm_has_mirrored_b_term,
    bterm_is_mirrored,
    bterm_is_set_mark,
    bterm_is_set_spef_mark,
    bterm_is_special,
    bterm_sta_vertex_id,
    inst_get_block,
    inst_get_child,
    inst_get_const_name,
    inst_get_eco_create,
    inst_get_eco_destroy,
    inst_get_eco_modify,
    inst_get_first_input,
    inst_get_first_output,
    inst_get_master,
    inst_get_name,
    inst_get_orient,
    inst_get_parent,
    inst_get_pin_access_idx,
    inst_get_placement_status,
    inst_get_region,
    inst_get_source_type,
    inst_get_user_flag1,
    inst_get_user_flag2,
    inst_get_user_flag3,
    inst_get_weight,
    inst_is_block,
    inst_is_core,
    inst_is_do_not_touch,
    inst_is_end_cap,
    inst_is_fixed,
    inst_is_hierarchical,
    inst_is_pad,
    inst_is_physical_only,
    inst_is_placed,
    iterm_get_b_term,
    iterm_get_block,
    iterm_get_ext_id,
    iterm_get_inst,
    iterm_get_io_type,
    iterm_get_m_term,
    iterm_get_mod_net,
    iterm_get_net,
    iterm_get_sig_type,
    iterm_is_clocked,
    iterm_is_connected,
    iterm_is_set_mark,
    iterm_is_special,
    iterm_is_spef,
    iterm_sta_vertex_id,
    layer_get_alias,
    layer_get_capacitance,
    layer_get_const_name,
    layer_get_edge_capacitance,
    layer_get_first_last_pitch,
    layer_get_layer_adjustment,
    layer_get_lef58_type_string,
    layer_get_lower_layer,
    layer_get_max_width,
    layer_get_min_step,
    layer_get_min_step_max_edges,
    layer_get_min_step_max_length,
    layer_get_min_width,
    layer_get_name,
    layer_get_num_masks,
    layer_get_number,
    layer_get_offset,
    layer_get_offset_x,
    layer_get_offset_y,
    layer_get_pitch,
    layer_get_pitch_x,
    layer_get_pitch_y,
    layer_get_protrusion_from_width,
    layer_get_protrusion_length,
    layer_get_protrusion_width,
    layer_get_resistance,
    layer_get_routing_level,
    layer_get_spacing,
    layer_get_tech,
    layer_get_two_widths_spacing_table_num_widths,
    layer_get_upper_layer,
    layer_get_width,
    layer_get_wire_extension,
    layer_get_wrong_way_min_width,
    layer_get_wrong_way_width,
    layer_has_alias,
    layer_has_area,
    layer_has_default_antenna_rule,
    layer_has_max_width,
    layer_has_min_step,
    layer_has_min_step_max_edges,
    layer_has_min_step_max_length,
    layer_has_orth_spacing_table,
    layer_has_oxide2_antenna_rule,
    layer_has_protrusion,
    layer_has_two_widths_spacing_rules,
    layer_has_v55_spacing_rules,
    layer_has_x_y_offset,
    layer_has_x_y_pitch,
    layer_is_backside,
    layer_is_rect_only,
    layer_is_rect_only_except_non_core_pins,
    layer_is_right_way_on_grid_only,
    layer_is_right_way_on_grid_only_check_mask,
    master_get_const_name,
    master_get_e_e_q,
    master_get_height,
    master_get_l_e_q,
    master_get_lib,
    master_get_m_term_count,
    master_get_master_id,
    master_get_name,
    master_get_site,
    master_get_symmetry_r90,
    master_get_symmetry_x,
    master_get_symmetry_y,
    master_get_width,
    master_is_backside_bridge,
    master_is_block,
    master_is_core,
    master_is_core_auto_placeable,
    master_is_cover,
    master_is_end_cap,
    master_is_filler,
    master_is_frozen,
    master_is_marked,
    master_is_pad,
    master_is_sequential,
    master_is_special_power,
    mterm_get_const_name,
    mterm_get_index,
    mterm_get_io_type,
    mterm_get_master,
    mterm_get_name,
    mterm_get_sig_type,
    mterm_has_default_antenna_model,
    mterm_has_oxide2_antenna_model,
    mterm_is_set_mark,
    ndr_get_const_name,
    ndr_get_hard_spacing,
    ndr_get_name,
    ndr_is_block_rule,
    net_find_mod_net_in_highest_hier,
    net_get1st_b_term,
    net_get1st_cap_node_id,
    net_get1st_i_term,
    net_get1st_r_seg_id,
    net_get_b_term_count,
    net_get_block,
    net_get_cap_node_count,
    net_get_cc_adjust_factor,
    net_get_cc_adjust_order,
    net_get_cc_calib_factor,
    net_get_cc_count,
    net_get_cc_match_ratio,
    net_get_const_name,
    net_get_db_cc,
    net_get_driving_i_term,
    net_get_first_driver_inst,
    net_get_first_output,
    net_get_gndc_calib_factor,
    net_get_i_term_count,
    net_get_name,
    net_get_non_default_rule,
    net_get_r_seg_count,
    net_get_ref_cc,
    net_get_sig_type,
    net_get_source_type,
    net_get_term_count,
    net_get_weight,
    net_get_wire_type,
    net_get_x_talk_class,
    net_has_fixed_bump,
    net_has_jumpers,
    net_is_connected_by_abutment,
    net_is_disconnected,
    net_is_do_not_touch,
    net_is_extracted,
    net_is_i_o,
    net_is_mark_1ed,
    net_is_marked,
    net_is_r_c_disconnected,
    net_is_r_cgraph,
    net_is_select,
    net_is_spef,
    net_is_wild_connected,
    net_is_wire_altered,
    net_is_wire_ordered,
    net_max_internal_cap_num,
    nth_block_get_b_terms,
    nth_block_get_children,
    nth_block_get_i_terms,
    nth_block_get_insts,
    nth_block_get_mod_nets,
    nth_block_get_nets,
    nth_block_get_non_default_rules,
    nth_block_get_regions,
    nth_block_get_rows,
    nth_block_get_vias,
    nth_inst_get_children,
    nth_inst_get_i_terms,
    nth_master_get_m_terms,
    nth_net_get_b_terms,
    nth_net_get_i_terms,
    num_block_get_b_terms,
    num_block_get_children,
    num_block_get_i_terms,
    num_block_get_insts,
    num_block_get_mod_nets,
    num_block_get_nets,
    num_block_get_non_default_rules,
    num_block_get_regions,
    num_block_get_rows,
    num_block_get_vias,
    num_inst_get_children,
    num_inst_get_i_terms,
    num_master_get_m_terms,
    num_net_get_b_terms,
    num_net_get_i_terms,
    row_get_block,
    row_get_const_name,
    row_get_name,
    row_get_orient,
    row_get_site,
    row_get_site_count,
    row_get_spacing,
    site_get_const_name,
    site_get_height,
    site_get_lib,
    site_get_name,
    site_get_symmetry_r90,
    site_get_symmetry_x,
    site_get_symmetry_y,
    site_get_width,
    site_has_row_pattern,
    site_is_hybrid,
    techvia_get_bottom_layer,
    techvia_get_const_name,
    techvia_get_name,
    techvia_get_non_default_rule,
    techvia_get_pattern,
    techvia_get_resistance,
    techvia_get_tech,
    techvia_get_top_layer,
    techvia_get_via_generate_rule,
    techvia_has_params,
    techvia_is_default,
    techvia_is_top_of_stack,
    via_get_block,
    via_get_block_via,
    via_get_bottom_layer,
    via_get_const_name,
    via_get_name,
    via_get_orient,
    via_get_pattern,
    via_get_tech_via,
    via_get_top_layer,
    via_get_via_generate_rule,
    via_has_params,
    via_is_default,
    via_is_via_rotated,
};
